# Auto-generated by ShowOnce
# Workflow: data_extraction
# Framework: Playwright

import asyncio
from playwright.async_api import async_playwright

async def run_data_extraction(search_term: str):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        page = await browser.new_page()
        
        try:
            # Step 1: Go to eBay
            await page.goto("https://www.ebay.com")
            
            # Step 2: Search for a product
            await page.fill("#gh-ac", search_term)
            
            # Step 3: Press Enter to search
            await page.keyboard.press("Enter")
            await page.wait_for_load_state("networkidle")
            
            # Step 4: Click on the first product result
            await page.click(".s-item__link")
            await page.wait_for_load_state("networkidle")
            
            # Data extraction phase
            # price = await page.inner_text(".x-price-primary")
            # print(f"Detected Price: {price}")
            
            print("Successfully navigated to product page!")

        finally:
            await browser.close()

if __name__ == "__main__":
    asyncio.run(run_data_extraction("vintage watch"))
