# Auto-generated by ShowOnce
# Workflow: form_submission
# Framework: Selenium

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select

def run_form_submission(full_name: str, user_email: str):
    driver = webdriver.Chrome()
    wait = WebDriverWait(driver, 10)
    
    try:
        # Step 1: Go to contact form
        driver.get("https://example.com/forms/contact")
        
        # Step 2: Input full name
        name_field = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#name")))
        name_field.send_keys(full_name)
        
        # Step 3: Input email address
        email_field = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#email")))
        email_field.send_keys(user_email)
        
        # Step 4: Select Sales department
        dept_dropdown = Select(driver.find_element(By.CSS_SELECTOR, "#dept"))
        dept_dropdown.select_by_visible_text("Sales")
        
        # Step 5: Subscribe to newsletter
        newsletter = driver.find_element(By.CSS_SELECTOR, "#newsletter")
        if not newsletter.is_selected():
            newsletter.click()
            
        # Step 6: Submit the form
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        
        time.sleep(2)
        print("Form submitted successfully!")

    finally:
        driver.quit()

if __name__ == "__main__":
    run_form_submission("John Doe", "john@example.com")
